### ISSUE TITLE
wizPurchase.restoreAll always return OK on android

### ISSUE THREAD

**Issue by ghost** [Wizcorp/phonegap-plugin-wizPurchase#25]
when I try to use wizPurchase.restoreAll(function (result) { alert("OK") }, function (error) { alert("NOT OK!") }); it always return OK..  (Non-consumeable)

makePurchase works as it should (returning error when no login, insufficient funds, etc).

restoreAll works as it should on iOS.

**Comment by alexbleks** [comment]
now its the same shit on iOS aswell.

**Comment by alexbleks** [comment]
wizPurchase.restoreAll(function (result) { alert("Restored: " + JSON.stringify(result)) }, function (error) { alert("Error:" + error) }); always returns "Restored: null"

**Comment by aogilvie** [comment]
@alexbleks Any luck? You can try debug this line https://github.com/Wizcorp/phonegap-plugin-wizPurchase/blob/develop/platforms/android/src/jp/wizcorp/phonegap/plugin/wizPurchase/WizPurchasePlugin.java#L411 looks like it could not get a list of purchases.

**Comment by jrouault** [comment]
Issue closed because:
- probably a duplicate of #20
- user deleted
- language
