### ISSUE TITLE
Typo in config.xml syntaxe

### ISSUE THREAD

**Issue by CyrilleGuimezanes** [Wizcorp/phonegap-plugin-wizPurchase#34]
Hello,

There is a small error into your config.xml definition:

`<variable name="BILLING_KEY" value="YOUR_BILLING_KEY" />`

Become:
`<param name="BILLING_KEY" value="YOUR_BILLING_KEY" />`

Regards,

**Comment by jrouault** [comment]
Hi,
Are you using Cordova or Phonegap? Which version are you on?
This was tested on Cordova 5.3.3 and Cordova-Android 4.1.1. Using ```param``` doesn't seem to work on those while ```variable``` works.

**Comment by CyrilleGuimezanes** [comment]
Hi,
According to some post on stackoverflow, you're right. 

For **Cordova** it's: variable
For **Phonegap/phonegap build** it's: param (which is use)

There a good exemple here: https://www.npmjs.com/package/cordova-plugin-customurlscheme 

I will do a PR on your README to add a "phonegap build" section on your readme

**Comment by jrouault** [comment]
I see, thanks again! A bit sad to learn that it isn't the same between the two. Looking forward to your changes. :+1:
