### ISSUE TITLE
Error: One or more SKU was not found in Google Inventory

### ISSUE THREAD

**Issue by CyrilleGuimezanes** [Wizcorp/phonegap-plugin-wizPurchase#35]
Hello,

I try to use your plugin but, on Android I get these logs: http://pastebin.com/kWM7HV4V 

What's mean "One or more Sku were not found in Google Inventory"? Did I miss something?

Regards,

**Comment by CyrilleGuimezanes** [comment]
I did some other test and edit log given at line 529 of WizPurchasePlugin.java to write the given and the needed SKU:


`D/WizPurchase(31597): One or more Sku were not found in Google Inventory`
`D/WizPurchase(31597): sku not found in Google Inventory: bargainadv.pack.building2 should be equal to: bargainadv.pack.premium1`
`D/WizPurchase(31597): sku not found in Google Inventory: bargainadv.pack.no.ads should be equal to: bargainadv.pack.building1`
`D/WizPurchase(31597): sku not found in Google Inventory: bargainadv.pack.premium1 should be equal to: bargainadv.pack.building2`
`D/WizPurchase(31597): sku not found in Google Inventory: bargainadv.pack.building1 should be equal to: bargainadv.pack.no.ads`


The SKU names are OK but not in the right order....

**Comment by jrouault** [comment]
Any idea why they were in the wrong order in the first place?

If you already worked on a fix, feel free to send a PR. Contributions are more than welcome. :+1:

**Comment by CyrilleGuimezanes** [comment]
There were in the wrong order because I gave an array to the function like:
['bargainadv.pack.building1', 'bargainadv.pack.building2', 'bargainadv.pack.no.ads', 'bargainadv.pack.premium1']

For the moment I just changed the order of elements in this array, this is absolutly not a good solution.

Instead of reorder Inventory and received SKUs it can be better to check if a given SKU ** is ** on the inventory (.contains() ).

If I have enough time, I try & PR

**Comment by jrouault** [comment]
Ok, I see, that indeed needs to be fixed. Thanks for your feedback!
We will work on a fix a bit later if you don't have time to PR it.

**Comment by jrouault** [comment]
Fixed in #39
