### ISSUE TITLE
Apple TestFlight - Feedback

### ISSUE THREAD

**Issue by CyrilleGuimezanes** [Wizcorp/phonegap-plugin-wizPurchase#37]
Hello,

Have you ever succefully test the plugin on Apple TestFlight. In my tests, my app crash but I'm not sure if it's because my IAP are not validated yet by Apple.

Any Feedback?

Regards,

**Comment by jrouault** [comment]
We currently have an app on Testflight using this plugin and we didn't have any report yet of a crash because of this plugin.

Do you have more information? A crash report?

**Comment by CyrilleGuimezanes** [comment]
Solved! 
IAP had to be validated before any use on testflight. 
Maybe the plugin can handle it (check apple api response in case of non validated iap)
Thx!

**Comment by jrouault** [comment]
Afaik we didn't have any issue with non-validated IAP on Testflight either. I'll investigate that asap. Thanks for the feedback!
